import { types } from 'mobx-state-tree';

export const TextElement = types
  .model('Textbox', {
    id: types.identifier,
    styles: types.array(types.frozen()),
    type: 'textbox',
    originX: 'left',
    originY: 'top',
    fill: 'rgb(0,0,0)',
    stroke: '',
    strokeWidth: 1,
    width: 100,
    height: 0,
    strokeDashArray: '',
    strokeLineCap: 'butt',
    strokeDashOffset: 0,
    strokeLineJoin: 'miter',
    strokeUniform: false,
    strokeMiterLimit: 4,
    scaleX: 1,
    scaleY: 1,
    angle: 0,
    flipX: false,
    flipY: false,
    shadow: '',
    backgroundColor: '',
    fillRule: 'nonzero',
    paintFirst: 'fill',
    globalCompositeOperation: 'source-over',
    skewX: 0,
    skewY: 0,
    fontFamily: 'arial',
    fontWeight: 'normal',
    fontSize: 80,
    text: '',
    underline: false,
    overline: false,
    linethrough: false,
    textAlign: 'left',
    fontStyle: 'normal',
    lineHeight: 1.16,
    textBackgroundColor: '',
    charSpacing: 0,
    direction: 'ltr',
    path: '',
    pathStartOffset: 0,
    pathSide: 'left',
    pathAlign: 'baseline',
    minWidth: 20,
    splitByGrapheme: true,
    selectable: true,
    hasControls: true,
    visible: true,
    opacity: 1,
    name: '',
  })
  .preProcessSnapshot((e) => Object.assign({}, e));
